# -*- coding: utf-8 -*-
"""2015_Arizona_energy_burden_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpY5SGoc_WUWTvf7SCB-ShX8Dh95wpqP
"""

#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#add data file
from google.colab import files
uploaded = files.upload()

#add data file
from google.colab import files
uploaded = files.upload()

#add data file
from google.colab import files
uploaded = files.upload()

"""# This section is working with the median household income by county in Arizona for 2015

"""

#inspect first data set
median_income_2015 = pd.read_csv("/content/2015 S1903MEDIAN INCOME (IN 2015 INFLATION-ADJUSTED DOLLARS).csv")

median_income_2015.shape

#inspect first data set
median_income_2015.head()

#inspect first data set
median_income_2015.columns

#inspect first data set
median_income_2015.info()

#dropping unneeded columns
drop_columns = [col for col in median_income_2015.columns if "Margin" in col]

clean_median_income_2015 = median_income_2015.drop(columns=drop_columns)

clean_median_income_2015.columns
clean_median_income_2015.head()

#check for null
clean_median_income_2015.isnull().sum()

clean_median_income_2015[clean_median_income_2015.isnull().any(axis=1)]

#drop null rows
clean_median_income_2015 = clean_median_income_2015.dropna()

clean_median_income_2015.head()

#renaming columns with function

def clean_column(col):
  parts = col.split("!!")

  #first row exception
  if col.startswith("Arizona!!Total"):
    return "Arizona population"

  #county columns
  if "County" in parts[0]:
    county = parts[0].split(",")[0].replace(" County", "").strip()
    metric = parts[1].strip() if len(parts) > 1 else ""

    if metric == "Total":
      metric = "population"
    elif metric == "Median income (dollar)":
      metric = "median income"

    return f"{county} {metric}"

  return col

clean_median_income_2015.columns = [clean_column(col) for col in clean_median_income_2015.columns]

clean_median_income_2015.head()

clean_median_income_2015.columns = list(map(lambda x: x.replace("Estimate", "median income"), clean_median_income_2015.columns))
clean_median_income_2015.columns = [(col.split("!!")[0] + "Median income") if "Median income" in col else col for col in clean_median_income_2015.columns]
clean_median_income_2015.head()

clean_median_income_2015 = clean_median_income_2015.iloc[:1]

clean_median_income_2015.reset_index(drop=True, inplace=True)

clean_median_income_2015.head()

"""# This section is working with EIA sales(electricity sales) by provider in Arizona for 2015 and will be sectioned by county below"""

#EIA data for 2015
EIA_sales_2015 = pd.read_excel("/content/EIA electricity Sales_Ult_Cust_2015.xlsx")
EIA_sales_2015.head()

#dropping all columns for non-residential customers
clean_EIA_2015 = EIA_sales_2015[["Utility Characteristics", "Unnamed: 1", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4", "Unnamed: 5", "Unnamed: 6", "Unnamed: 7", "Unnamed: 8","RESIDENTIAL",  "Unnamed: 10","Unnamed: 11"]]
clean_EIA_2015.head()

top = clean_EIA_2015.iloc[0].fillna("")
bottom = clean_EIA_2015.iloc[1].fillna("")
clean_EIA_2015.columns = [
    f"{a} {b}".strip() if a != "" else b
    for a, b in zip(top, bottom)
]

clean_EIA_2015 = clean_EIA_2015.iloc[2:].reset_index(drop=True)

clean_EIA_2015.head()

clean_EIA_2015 = clean_EIA_2015[["Data Year","Utility Number", "Utility Name", "State","Revenues Thousand Dollars","Sales Megawatthours","Customers Count"]]

clean_EIA_2015_az = clean_EIA_2015[clean_EIA_2015["State"] == "AZ"]
clean_EIA_2015_az.head()

clean_EIA_2015_az.dropna(inplace=True)
clean_EIA_2015_az.head()

clean_EIA_2015_az= clean_EIA_2015_az.replace(".", np.nan)
clean_EIA_2015_az = clean_EIA_2015_az.dropna()
clean_EIA_2015_az.head()

clean_EIA_2015_az.dtypes

clean_EIA_2015_az.shape

"""This section uploads a mapping file to add county column to EIA sales data. This will allow the grouping of data by county. This section concludes in merging median income and EIA data by county"""

from google.colab import files
uploaded = files.upload()

utility_with_county = pd.read_csv("/content/Utilities with counties.csv")
utility_with_county.head()

#keep only the yes values and needed columns
utility_with_county = utility_with_county[utility_with_county["Value"] == "Yes"].copy()

utility_with_county = utility_with_county.rename(columns={
    "Attribute": "Utility Name",
    "Counties": "County"
})
utility_with_county = utility_with_county[["Utility Name", "County"]]

utility_with_county.head()

utility_with_county["Utility Name"].unique()

clean_EIA_2015_az["Utility Name"].unique()

county_EIA_2015_az = clean_EIA_2015_az
county_EIA_2015_az.head()

#fix naming differnces
county_EIA_2015_az["Utility Name"] = (county_EIA_2015_az["Utility Name"].astype(str).str.strip().str.lower())
utility_with_county["Utility Name"] = (utility_with_county["Utility Name"].astype(str).str.strip().str.lower())

name_fixes = {
     "ajo improvement co": "ajo improvement company",
    "arizona public service co": "arizona public service",
    "columbus electric coop, inc": "columbus electric co-op",
    "dixie escalante r e a, inc": "dixie escalante rural electric association",
    "garkane energy coop, inc": "garkane power association",
    "graham county electric coop inc": "graham county electric cooperative",
    "mohave electric cooperative, inc": "mohave electric cooperative",
    "morenci water and electric co": "morenci water & electric company",
    "navopache electric coop, inc": "navopache electric co-op",
    "sulphur springs valley e c inc": "sulphur springs valley electric co-op",
    "trico electric cooperative inc": "trico electric cooperative",
    "tucson electric power co": "tucson electric power",
    "uns electric, inc": "uns electric inc.",
    "city of mesa ": "city of mesa",
    "city of mesa - (az)": "city of mesa",
    "morenci water and electric": "morenci water & electric company",
    "page utility enterprises": "page electric utility",
    "electrical dist no2 pinal county": "electrical dist no2 pinal cnty",
    "electrical dist no3 pinal county": "electrical dist no3 pinal cnty",
    "electrical dist no4 pinal county": "electrical dist no4 pinal cnty",
    "mohave electric cooperative, i": "mohave electric cooperative"
}
county_EIA_2015_az["Utility Name"] = county_EIA_2015_az["Utility Name"].replace(name_fixes)
utility_with_county["Utility Name"] = utility_with_county["Utility Name"].replace(name_fixes)
county_EIA_2015_az.head()

county_EIA_2015_az = county_EIA_2015_az.merge( utility_with_county, on="Utility Name", how="left")
county_EIA_2015_az.head()

#checking missing counties
county_EIA_2015_az.isna().sum()
missing = county_EIA_2015_az[county_EIA_2015_az["County"].isna()]
missing["Utility Name"].unique()
#based on the output, these companies will be dropped as they are not residental power suppliers

county_EIA_2015_az= county_EIA_2015_az.dropna()
county_EIA_2015_az.head()

#aggregate to county level
county_summary_2015 = (
    county_EIA_2015_az
    .groupby(["Data Year", "County"], as_index=False)
    .agg({
        "Revenues Thousand Dollars": "sum",
        "Sales Megawatthours": "sum",
        "Customers Count": "sum"
    })
    )

county_summary_2015["County"] = (county_summary_2015["County"].str.lower())
county_summary_2015.head()

#transforming wide dataframe into long data frame for merge
row = clean_median_income_2015.iloc[0]

records = []

clean_median_income_2015.columns = clean_median_income_2015.columns.str.strip()

for col in clean_median_income_2015.columns:
  col_clean = col.strip()

  if col_clean == "Label (Grouping)":
    continue
  if col_clean.lower().startswith("arizona"):
    continue

  if " population" in col_clean:
    county = col_clean.lower().replace(" population", "").strip()
    population = row[col]

    matching_income_col = [
        c for c in clean_median_income_2015.columns
        if c.lower().startswith(county) and "median income" in c.lower()
    ]

    median_income = row[matching_income_col[0]] if matching_income_col else None

    records.append({
        "County": county,
        "Population": population,
        "Median Income": median_income
    })

income_2015_long = pd.DataFrame(records)
income_2015_long.head()

clean_2015 = county_summary_2015.merge(income_2015_long, on="County")
clean_2015.head()

"""# This section is working with the percent of income for housing by county in Arizona for 2015"""

housing_2015 = pd.read_csv("/content/Financial Characteristics for Housing Units with and without a Mortgage 2015.csv")
housing_2015.head()

housing_2015 = housing_2015.loc[:, ~housing_2015.columns.str.contains("Margin of Error", case=False)]
housing_2015

cleaning_housing_2015 = housing_2015.copy()
cleaning_housing_2015.rename(columns={"Label (Grouping)": "Label"}, inplace=True)
cleaning_housing_2015

#convert string numbers to numeric
for col in cleaning_housing_2015.columns[1:]:
  cleaning_housing_2015[col] = (
      cleaning_housing_2015[col]
      .astype(str)
      .str.replace(",", "", regex=False)
      .astype(float)
  )
cleaning_housing_2015.head()

#sum percent category
def sum_by_label(df):
  return(
      df
      .groupby("Label", as_index=False)
      .sum(numeric_only=True)
  )
grouped_housing_2015 = sum_by_label(cleaning_housing_2015)
grouped_housing_2015

#drop unneeded rows
grouped_housing_2015["Label"] = (
    grouped_housing_2015["Label"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.lower()
    .str.strip()
)
grouped_housing_2015 = grouped_housing_2015[ ~grouped_housing_2015["Label"].isin(["total:","not computed","housing units with a mortgage:","housing units without a mortgage:"])].copy()
grouped_housing_2015

from pandas.core import groupby
#binning percents so that they are more manageable
def assign_bin(label):
  if label in [
      "less than 10.0 percent",
      "10.0 to 14.9 percent",
      "15.0 to 19.9 percent",
      "20.0 to 24.9 percent",
      "25.0 to 29.9 percent",

  ]:
      return "les_30"
  elif label in [
      "30.0 to 34.9 percent",
      "35.0 to 39.9 percent",
      "40.0 to 49.9 percent",

  ]:
      return "30_50"
  elif label == "50.0 percent or more":
      return "grt_50"

  return None

#apply binning function to create new column
grouped_housing_2015["bin"] = grouped_housing_2015["Label"].apply(assign_bin)

#aggregate bins
binned_housing_2015 = (
    grouped_housing_2015
    .groupby("bin", as_index=False)
    .sum(numeric_only=True)
)

#order bins
order = ["les_30", "30_50", "grt_50"]
binned_housing_2015["bin"] = pd.Categorical(binned_housing_2015["bin"], categories=order, ordered=True)

binned_housing_2015 = binned_housing_2015.sort_values("bin").reset_index(drop=True)
binned_housing_2015

#create long dataset and clean county names for final step before final merge
housing_long = binned_housing_2015.melt(
    id_vars=["bin"],
    var_name="County",
    value_name="Population_Bin_Count"
)

#drop the total row(can be recalculated if needed)
housing_long = housing_long[housing_long["County"] != "arizona"].copy()

housing_long["County"] = (
    housing_long["County"]
    .str.replace("County, Arizona!!Total population!!Estimate", "", regex=False)
    .str.replace("!!Total population!!Estimate", "", regex=False)
    .str.strip()
    .str.lower()
)
housing_long

#pivot housing long into usable form for merge
housing_final = (
    housing_long
    .pivot(index="County", columns="bin", values="Population_Bin_Count")
    .reset_index()
)

#rename columns to clean titles
housing_final = housing_final.rename(columns={
    "les_30": "less than 30 percent income in housing cost",
    "30_50": "30 to 50 percent income in housing cost",
    "grt_50": "greater than 50 percent income in housing cost"
})

#add data year for final merge
housing_final["Data Year"] = 2015

#reorder columns
housing_final = housing_final[
    ["Data Year","County","less than 30 percent income in housing cost","30 to 50 percent income in housing cost","greater than 50 percent income in housing cost"]
]
housing_final.head()

#creating final dataset for 2015
clean_year_2015 = clean_2015.merge(
    housing_final,
    on=["Data Year", "County"],
    how="left"
)
clean_year_2015

#save final set as csv
clean_year_2015.to_csv("clean_year_2015.csv", index=False)
from google.colab import files
files.download("clean_year_2015.csv")