# -*- coding: utf-8 -*-
"""2024_Arizona_energy_burden_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLEKH67Y-iO4rLNHvhoM-SrJ6hfj5D93
"""

#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#add data file
from google.colab import files
uploaded = files.upload()

#add data file
from google.colab import files
uploaded = files.upload()

#add data file
from google.colab import files
uploaded = files.upload()

#add data file
from google.colab import files
uploaded = files.upload()

"""# This section is working with the median household income by county in Arizona for 2024

"""

#inspect first data set
median_income_2024 = pd.read_csv("/content/2024 S1903MEDIAN INCOME (IN 2024 INFLATION-ADJUSTED DOLLARS).csv")

median_income_2024.shape

#inspect first data set
median_income_2024.head()

#inspect first data set
median_income_2024.columns

#inspect first data set
median_income_2024.info()

#dropping unneeded columns
drop_columns = [col for col in median_income_2024.columns if "Margin" in col]

clean_median_income_2024 = median_income_2024.drop(columns=drop_columns)

clean_median_income_2024.columns
clean_median_income_2024.head()

#check for null
clean_median_income_2024.isnull().sum()

clean_median_income_2024[clean_median_income_2024.isnull().any(axis=1)]

#drop null rows
clean_median_income_2024 = clean_median_income_2024.dropna()

clean_median_income_2024.head()

#renaming columns with function (reworked from previous years to incorporate new columns)
clean_median_income_2024 = clean_median_income_2024.drop(columns=[col for col in clean_median_income_2024.columns if "Percent Distribution" in col])

def clean_column(col):
  col = str(col).strip()
  parts = col.split("!!")

  #keeping row label
  if col == "Label (Grouping)":
    return "Label"

  #Arizona total columns
  if parts[0].strip() == "Arizona":
    metric = parts[1].strip().lower() if len(parts) > 1 else ""

    if metric == "number":
      return "Arizona population"
    elif metric == "median income (dollars)":
      return "Arizona median income"

  #county columns
  if "County" in parts[0]:
    county = parts[0].split(",")[0].replace(" County", "").strip().lower()
    metric = parts[1].strip().lower() if len(parts) > 1 else ""

    if metric == "number":
      metric = "population"
    elif metric == "median income (dollars)":
      metric = "median income"

    return f"{county} {metric}"

  return col

clean_median_income_2024.columns = [clean_column(col) for col in clean_median_income_2024.columns]

clean_median_income_2024.head()

clean_median_income_2024 = clean_median_income_2024.iloc[:1]

clean_median_income_2024.reset_index(drop=True, inplace=True)

clean_median_income_2024.head()

"""# This section is working with EIA sales(electricity sales) by provider in Arizona for 2024 and will be sectioned by county below"""

#EIA data for 2024
EIA_sales_2024 = pd.read_excel("/content/EIA electricity Sales_Ult_Cust_2024.xlsx")
EIA_sales_2024.head()

#dropping all columns for non-residential customers
clean_EIA_2024 = EIA_sales_2024[["Utility Characteristics", "Unnamed: 1", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4", "Unnamed: 5", "Unnamed: 6", "Unnamed: 7", "Unnamed: 8","RESIDENTIAL",  "Unnamed: 10","Unnamed: 11"]]
clean_EIA_2024.head()

top = clean_EIA_2024.iloc[0].fillna("")
bottom = clean_EIA_2024.iloc[1].fillna("")
clean_EIA_2024.columns = [
    f"{a} {b}".strip() if a != "" else b
    for a, b in zip(top, bottom)
]

clean_EIA_2024 = clean_EIA_2024.iloc[2:].reset_index(drop=True)

clean_EIA_2024.head()

clean_EIA_2024 = clean_EIA_2024[["Data Year","Utility Number", "Utility Name", "State","Revenues Thousand Dollars","Sales Megawatthours","Customers Count"]]

clean_EIA_2024_az = clean_EIA_2024[clean_EIA_2024["State"] == "AZ"]
clean_EIA_2024_az.head()

clean_EIA_2024_az.dropna(inplace=True)
clean_EIA_2024_az.head()

clean_EIA_2024_az= clean_EIA_2024_az.replace(".", np.nan)
clean_EIA_2024_az = clean_EIA_2024_az.dropna()
clean_EIA_2024_az.head()

#checking that the number columns return float type (no strings)
clean_EIA_2024_az.dtypes

clean_EIA_2024_az.shape

"""This section uploads a mapping file to add county column to EIA sales data. This will allow the grouping of data by county. This section concludes in merging median income and EIA data by county"""

from google.colab import files
uploaded = files.upload()

utility_with_county = pd.read_csv("/content/Utilities with counties.csv")
utility_with_county.head()

#keep only the yes values and needed columns
utility_with_county = utility_with_county[utility_with_county["Value"] == "Yes"].copy()

utility_with_county = utility_with_county.rename(columns={
    "Attribute": "Utility Name",
    "Counties": "County"
})
utility_with_county = utility_with_county[["Utility Name", "County"]]

utility_with_county.head()

utility_with_county["Utility Name"].unique()

clean_EIA_2024_az["Utility Name"].unique()

county_EIA_2024_az = clean_EIA_2024_az
county_EIA_2024_az.head()

#fix naming differnces
county_EIA_2024_az["Utility Name"] = (county_EIA_2024_az["Utility Name"].astype(str).str.strip().str.lower())
utility_with_county["Utility Name"] = (utility_with_county["Utility Name"].astype(str).str.strip().str.lower())

name_fixes = {
     "ajo improvement co": "ajo improvement company",
    "arizona public service co": "arizona public service",
    "columbus electric coop, inc": "columbus electric co-op",
    "dixie escalante r e a, inc": "dixie escalante rural electric association",
    "garkane energy coop, inc": "garkane power association",
    "graham county electric coop inc": "graham county electric cooperative",
    "mohave electric cooperative, inc": "mohave electric cooperative",
    "morenci water and electric co": "morenci water & electric company",
    "navopache electric coop, inc": "navopache electric co-op",
    "sulphur springs valley e c inc": "sulphur springs valley electric co-op",
    "trico electric cooperative inc": "trico electric cooperative",
    "tucson electric power co": "tucson electric power",
    "uns electric, inc": "uns electric inc.",
    "city of mesa ": "city of mesa",
     "city of mesa - (az)": "city of mesa",
    "morenci water and electric": "morenci water & electric company",
    "electrical dist no2 pinal county": "electrical dist no2 pinal cnty",
    "electrical dist no3 pinal county": "electrical dist no3 pinal cnty",
    "mohave electric cooperative, inc.": "mohave electric cooperative"
}
county_EIA_2024_az["Utility Name"] = county_EIA_2024_az["Utility Name"].replace(name_fixes)
utility_with_county["Utility Name"] = utility_with_county["Utility Name"].replace(name_fixes)
county_EIA_2024_az.head()

county_EIA_2024_az = county_EIA_2024_az.merge( utility_with_county, on="Utility Name", how="left")
county_EIA_2024_az.head()

#checking missing counties
county_EIA_2024_az.isna().sum()
missing = county_EIA_2024_az[county_EIA_2024_az["County"].isna()]
missing['Utility Name'].unique()
#based on these results all of these companies need to be dropped because they are not residential electric suppliers

county_EIA_2024_az= county_EIA_2024_az.dropna()
county_EIA_2024_az.head()

#aggregate to county level
county_summary_2024 = (
    county_EIA_2024_az
    .groupby(["Data Year", "County"], as_index=False)
    .agg({
        "Revenues Thousand Dollars": "sum",
        "Sales Megawatthours": "sum",
        "Customers Count": "sum"
    })
    )

county_summary_2024["County"] = (county_summary_2024["County"].str.lower())
county_summary_2024.head()

#transforming wide dataframe into long data frame for merge
row = clean_median_income_2024.iloc[0]

records = []

clean_median_income_2024.columns = clean_median_income_2024.columns.str.strip()

for col in clean_median_income_2024.columns:
  col_clean = col.strip()

  if col_clean == "Label (Grouping)":
    continue
  if col_clean.lower().startswith("arizona"):
    continue

  if " population" in col_clean:
    county = col_clean.lower().replace(" population", "").strip()
    population = row[col]

    matching_income_col = [
        c for c in clean_median_income_2024.columns
        if c.lower().startswith(county) and "median income" in c.lower()
    ]

    median_income = row[matching_income_col[0]] if matching_income_col else None

    records.append({
        "County": county,
        "Population": population,
        "Median Income": median_income
    })

income_2024_long = pd.DataFrame(records)
income_2024_long.head()

clean_2024 = county_summary_2024.merge(income_2024_long, on="County")
clean_2024.head()

"""# This section is working with the percent of income for housing by county in Arizona for 2024
Because these files vary significantly from the 2 previous years, additional cleaning is need including merging datasets before continuing with cleaning.
"""

housing_2024_without = pd.read_csv("/content/Financial Characteristics for Housing Units without a Mortgage 2024.csv")
housing_2024_with = pd.read_csv("/content/Financial characterisitics for Housing units with a Morgage 2024.csv")
housing_2024_without
#housing_2024.head()

#stripping extra spaces and checking output
housing_2024_with["Label (Grouping)"] = (housing_2024_with["Label (Grouping)"]
.astype(str)
.str.replace("\xa0", "", regex=False)
.str.replace(r"\s+"," ", regex=True)
.str.strip()
.str.lower()
)
print(housing_2024_with["Label (Grouping)"].unique())

"""###Housing with mortgage file cleaning section"""

print(housing_2024_with.columns.tolist())
housing_2024_with.isna().sum()

from numpy._core import numeric
#need to drop extra rows not part of cost of housing
drop_labels = [
  'owner-occupied housing units with a mortgage', 'value',
 'less than $50,000', '$50,000 to $99,999', '$100,000 to $299,999',
 '$300,000 to $499,999', '$500,000 to $749,999', '$750,000 to $999,999',
 '$1,000,000 or more', 'median (dollars)', 'mortgage status',
 'with either a second mortgage, or home equity loan, but not both',
 'second mortgage only', 'home equity loan only',
 'both second mortgage and home equity loan',
 'no second mortgage and no home equity loan',
 'household income in the past 12 months (in 2024 inflation-adjusted dollars)',
 'less than $10,000', '$10,000 to $24,999', '$25,000 to $34,999',
 '$35,000 to $49,999', '$50,000 to $74,999', '$75,000 to $99,999',
 '$100,000 to $149,999', '$150,000 or more',
 'median household income (dollars)',
 'ratio of value to household income in the past 12 months',
 'less than 2.0', '2.0 to 2.9', '3.0 to 3.9', '4.0 or more', 'not computed',
 'monthly housing costs', 'less than $200', '$200 to $399', '$400 to $599',
 '$600 to $799', '$800 to $999', '$1,000 to $1,499', '$1,500 to $1,999',
 '$2,000 to $2,499', '$2,500 to $2,999', '$3,000 or more',
 'monthly housing costs as a percentage of household income in the past 12 months',
 'less than $20,000','$20,000 to $34,999', '$75,000 or more',
 'zero or negative income', 'real estate taxes', 'less than $800',
 '$800 to $1,499', '$1,500 or more', 'no real estate taxes paid'
]

housing_2024_with = housing_2024_with[~housing_2024_with["Label (Grouping)"].isin(drop_labels)].copy()

#need to drop extra columns
housing_2024_with = housing_2024_with.drop(columns=[col for col in housing_2024_with.columns if "Margin of Error" in col or "Percent" in col])

#need to clean column titles
def clean_column_with(col):
  col = str(col).strip()
  parts = col.split("!!")

  #row label column
  if col == "Label (Grouping)":
    return "Label"

  geo = parts[0].split(",")[0].replace("County","").strip().lower()

  if len(parts) > 1:
    metric = parts[1].strip().lower()

    if "owner-occupied housing units with a mortgage" in metric:
      return f"{geo} total"
    elif "monthly housing costs" in metric:
      return f"{geo} monthly housing cost"
    elif "monthly housing costs as a percentage of housegold income" in metric:
      return f"{geo} housing cost pct income"
    elif "real estate taxes" in metric:
      return f"{geo} real estate taxes"

  return col
housing_2024_with.columns = [clean_column_with(col) for col in housing_2024_with.columns]

#need to change to numeric values
for col in housing_2024_with.columns:
  if col != "Label":
    housing_2024_with[col] = pd.to_numeric(
        housing_2024_with[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip(),
        errors="coerce"
    )

#summing rows
housing_2024_with = (
    housing_2024_with
    .groupby("Label", as_index=False)
    .sum(numeric_only=True)
)
housing_2024_with

"""###Housing without mortgage file cleaning section"""

print(housing_2024_without.columns.tolist())
#need to drop extra columns
housing_2024_without = housing_2024_without.drop(columns=[col for col in housing_2024_without.columns if "Margin of Error" in col or "Percent" in col])
print(housing_2024_without.columns.tolist())

housing_2024_without.isna().sum()

housing_2024_without.head()

#stripping extra spaces and checking output
housing_2024_without["Label (Grouping)"] = (housing_2024_without["Label (Grouping)"]
.astype(str)
.str.replace("\xa0", "", regex=False)
.str.replace(r"\s+"," ", regex=True)
.str.strip()
.str.lower()
)
print(housing_2024_without["Label (Grouping)"].unique())

#need to drop extra rows not part of cost of housing
drop_labels = [
  'owner-occupied housing units without a mortgage', 'value',
 'less than $50,000', '$50,000 to $99,999', '$100,000 to $199,999',
 '$200,000 to $299,999', '$300,000 to $499,999', '$500,000 to $749,999',
 '$750,000 to $999,999', '$1,000,000 or more', 'median (dollars)',
 'household income in the past 12 months (in 2024 inflation-adjusted dollars)',
 'less than $10,000', '$10,000 to $24,999', '$25,000 to $34,999',
 '$35,000 to $49,999', '$50,000 to $74,999', '$75,000 to $99,999',
 '$100,000 to $149,999', '$150,000 or more',
 'median household income (dollars)',
 'ratio of value to household income in the past 12 months',
 'less than 2.0', '2.0 to 2.9', '3.0 to 3.9', '4.0 or more', 'not computed',
 'monthly housing costs', 'less than $200', '$200 to $399', '$400 to $599',
 '$600 to $999', '$1,000 to $1,299', '$1,300 to $1,499', '$1,500 or more',
 'monthly housing costs as a percentage of household income in the past 12 months',
 'less than $20,000', '$20,000 to $34,999', '$75,000 or more',
 'zero or negative income', 'real estate taxes', 'less than $800',
 '$800 to $1,499', 'no real estate taxes paid'
]
housing_2024_without = housing_2024_without[~housing_2024_without["Label (Grouping)"].isin(drop_labels)].copy()

#need to drop extra columns
housing_2024_without = housing_2024_without.drop(columns=[col for col in housing_2024_without.columns if "Margin of Error" in col or "Percent" in col])

#need to clean column titles
def clean_column_with(col):
  col = str(col).strip()
  parts = col.split("!!")

  #row label column
  if col == "Label (Grouping)":
    return "Label"

  geo = parts[0].split(",")[0].replace("County","").strip().lower()

  if len(parts) > 1:
    metric = parts[1].strip().lower()

    if "owner-occupied housing units without a mortgage" in metric:
      return f"{geo} total"
    elif "monthly housing costs" in metric:
      return f"{geo} monthly housing cost"
    elif "monthly housing costs as a percentage of household income" in metric:
      return f"{geo} housing cost pct income"
    elif "real estate taxes" in metric:
      return f"{geo} real estate taxes"

  return col
housing_2024_without.columns = [clean_column_with(col) for col in housing_2024_without.columns]

#need to change to numeric values
for col in housing_2024_without.columns:
  if col != "Label":
    housing_2024_without[col] = pd.to_numeric(
        housing_2024_without[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip(),
        errors="coerce"
    )

#sum matching rows
for col in housing_2024_without.columns:
  if col != "Label":
    housing_2024_without[col] = pd.to_numeric(housing_2024_without[col], errors="coerce")

housing_2024_without = (
    housing_2024_without
    .groupby("Label", as_index=False)
    .sum(numeric_only=True)
)
housing_2024_without.head()

"""##The below section will merge the 2 sepearte housing datasets"""

#create inital merge
housing_2024 = housing_2024_without.merge(housing_2024_with, on="Label", how="outer", suffixes=("_without", "_with"))

#sorting columns and making one master list to us in for loop below
all_base_cols =sorted(
    set(housing_2024_without.columns).union(set(housing_2024_with.columns)) - {"Label"}
)
#create summed columns as final columns to be kept
for col in all_base_cols:
  col_without = f"{col}_without"
  col_with = f"{col}_with"

  if col_without in housing_2024.columns and col_with in housing_2024.columns:
    housing_2024[col] = (
        housing_2024[col_without].fillna(0) +
        housing_2024[col_with].fillna(0)
    )
  elif col_without in housing_2024.columns:
    housing_2024[col] = housing_2024[col_without]
  elif col_with in housing_2024.columns:
    housing_2024[col] = housing_2024[col_with]
#check that summed columns worked
housing_2024
#verified sum columns worked had to convert to table to see all columns for verification

#dropping orignal columns and keeping only total columns
housing_2024.columns = housing_2024.columns.str.strip()
total_cols = [col for col in housing_2024.columns
              if col == "Label" or (col.endswith("total") and not col.endswith("_with") and not col.endswith("_without"))]
#print(total_cols) used to check correct columns selected
housing_2024 = housing_2024[total_cols]
housing_2024

#create long dataset and clean county names for final step before final merge
housing_long = housing_2024.melt(
    id_vars=["Label"],
    var_name="County",
    value_name="Household_Count"
)

#clean county names
housing_long["County"] = (
    housing_long["County"]
    .str.replace("total", "", regex=False)
    .str.strip()
    .str.lower()
)
housing_long.head()

#pivot housing long into usable form for merge
housing_final = (
    housing_long
    .pivot(index="County", columns="Label", values="Household_Count")
    .reset_index()
)

#rename columns to clean titles
housing_final = housing_final.rename(columns={
    "20 to 29 percent": "20 to 29 percent income in housing cost",
    "30 percent or more": "greater than 30 percent income in housing cost",
    "less than 20 percent": "less than 20 percent income in housing cost"
})

#add data year for final merge
housing_final["Data Year"] = 2024

#reorder columns
housing_final = housing_final[
    ["Data Year","County","less than 20 percent income in housing cost","20 to 29 percent income in housing cost","greater than 30 percent income in housing cost"]
]
housing_final.head()

#creating final dataset for 2024
clean_year_2024 = clean_2024.merge(
    housing_final,
    on=["Data Year", "County"],
    how="left"
)
clean_year_2024

#save final set as csv
clean_year_2024.to_csv("clean_year_2024.csv", index=False)
from google.colab import files
files.download("clean_year_2024.csv")