# -*- coding: utf-8 -*-
"""Arizona_energy_burden_Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMQ4nQefchu1xPect_pYVkJtCFCY0_UB

#Exploratory Analysis Section

##Notebook setup, importing, data checking
"""

#import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import matplotlib.pyplot as plt

#upload data
from google.colab import files
uploaded = files.upload()

#upload data
from google.colab import files
uploaded = files.upload()

#upload data
from google.colab import files
uploaded = files.upload()

#load data
data_all_years = pd.read_csv('data_all_years.csv')
data_2010_2015 = pd.read_csv('2010_2015_data.csv')
data_2018_2020_2024 = pd.read_csv('2018_2020_2024_data.csv')

#check data loads
data_all_years.head()

#check data loads
data_2010_2015.head()

#check data loads
data_2018_2020_2024.head()

"""##Linear regression of data all years

"""

feature_cols = ["median_income","price_per_kwh","kwh_per_capita","data_year"]
target_col = "energy_burden"

X = data_all_years[feature_cols]
y = data_all_years[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

y_pred = lin_reg.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mse)

print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("Mean Absolute Error:", mae)
print("R-squared:", r2)

coef_all_years = pd.DataFrame({'Feature': feature_cols, 'Coefficient': lin_reg.coef_})

print("Intercept: ", lin_reg.intercept_)
coef_all_years

results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
results.head(10)

plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred)
min_val = min(min(y_test), min(y_pred))
max_val = max(max(y_test), max(y_pred))
plt.plot([min_val, max_val], [min_val, max_val], color='red', linestyle='--')
plt.xlabel('Actual Energy Burden')
plt.ylabel('Predicted Energy Burden')
plt.title('Actual vs. Predicted Energy Burden')
plt.savefig("figure_1_actual_vs_predicted_energy_burden",dpi=300, bbox_inches="tight")
plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(10, 6))
plt.scatter(y_test, residuals)
plt.axhline(y=0, color='r', linestyle='--')
plt.xlabel('Predicted Energy Burden')
plt.ylabel('Residuals')
plt.title('Residual Plot')
plt.savefig("figure_2_residual_plot",dpi=300, bbox_inches="tight")
plt.show()

#correlation of median income and energy burden
data_all_years[["median_income", "energy_burden"]].corr()

from pandas.io.formats.style_render import Subset
#energy burden versus median income by county
plt.figure(figsize=(10, 6))

for county in data_all_years['county'].unique():
    subset = data_all_years[data_all_years['county'] == county]
    plt.scatter(subset['median_income'], subset['energy_burden'], label=county)

plt.xlabel('Median Income')
plt.ylabel('Energy Burden')
plt.title('Energy Burden vs. Median Income by County')
plt.legend()
plt.savefig("figure_3_energy_burden_vs_income_county",dpi=300, bbox_inches="tight")
plt.show()

years = sorted(data_all_years["data_year"].unique())

fig, axes = plt.subplots(1, len(years), figsize=(16, 5))

for i, year in enumerate(years):
    subset = data_all_years[data_all_years["data_year"] == year]

    axes[i].scatter(
        subset["median_income"],
        subset["energy_burden"]
    )

    # trend line
    m, b = np.polyfit(subset["median_income"], subset["energy_burden"], 1)
    axes[i].plot(subset["median_income"], m * subset["median_income"] + b)

    axes[i].set_title(f"Year {year}")
    axes[i].set_xlabel("Median Income")
    axes[i].set_ylabel("Energy Burden")

for _, row in subset.iterrows():
    if row["energy_burden"] > subset["energy_burden"].quantile(0.75):
        axes[i].text(
            row["median_income"],
            row["energy_burden"],
            row["county"],
            fontsize=9
        )
plt.tight_layout()
plt.savefig("figure_4_median_income_vs_enery_burden_year",dpi=300, bbox_inches="tight")
plt.show()

counties = sorted(data_all_years["county"].unique())
years = sorted(data_all_years["data_year"].unique())

# rainbow colors for years
colors = plt.cm.rainbow(np.linspace(0, 1, len(years)))

# global axis limits
x_min, x_max = data_all_years["median_income"].min(), data_all_years["median_income"].max()
y_min, y_max = data_all_years["energy_burden"].min(), data_all_years["energy_burden"].max()

# 👇 changed layout
cols = 3
rows = int(np.ceil(len(counties) / cols))

# 👇 bigger figure size
fig, axes = plt.subplots(rows, cols, figsize=(24, rows * 5))
axes = axes.flatten()

for i, county in enumerate(counties):
    subset = data_all_years[data_all_years["county"] == county].sort_values("data_year")

    # connecting line
    axes[i].plot(
        subset["median_income"],
        subset["energy_burden"],
        color="gray",
        linewidth=1.5
    )

    for (year, color) in zip(years, colors):
        year_subset = subset[subset["data_year"] == year]

        axes[i].scatter(
            year_subset["median_income"],
            year_subset["energy_burden"],
            color=color,
            label=str(year)
        )

        # year labels
        for _, row in year_subset.iterrows():
            axes[i].annotate(
                str(int(row["data_year"])),
                (row["median_income"], row["energy_burden"]),
                xytext=(5, 5),
                textcoords="offset points",
                fontsize=8
            )

    axes[i].set_title(county)
    axes[i].set_xlabel("Median Income")
    axes[i].set_ylabel("Energy Burden")

    # force same axes
    axes[i].set_xlim(x_min, x_max)
    axes[i].set_ylim(y_min, y_max)

# remove empty plots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

# shared legend
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, title="Year", loc="upper right")

plt.tight_layout()
plt.savefig("figure_5_median_income_vs_energy_burden_county_multiplot",dpi=300, bbox_inches="tight")
plt.show()

"""## ***Since energy burden shows a decrease across most counties in recent years, further anaylsis is need to verify why energy burden has been decreasing**

##Energy Usagage analysis
"""

#checking total usage after energy burden shows decrease
total_usage = (
    data_all_years
    .groupby("data_year")["sales_megawatthours"]
    .sum()
    .reset_index()
)

plt.figure()
plt.plot(total_usage["data_year"], total_usage["sales_megawatthours"])
plt.xlabel("Year")
plt.ylabel("Total Usage (Megawatthours)")
plt.title("Total Usage Over Time")
plt.savefig("figure_6_energy_usage_over_time",dpi=300, bbox_inches="tight")
plt.show()

#checking usage by county over time
county_usage =(
    data_all_years
    .groupby(["county", "data_year"])["sales_megawatthours"]
    .sum()
    .reset_index()
)

county_usage_pivot = county_usage.pivot(
    index="data_year",
    columns="county",
    values="sales_megawatthours"
)

plt.figure()
county_usage_pivot.plot()
plt.xlabel("Year")
plt.ylabel("Total Usage (Megawatthours)")
plt.title("Total Usage by County Over Time")
plt.savefig("figure_7_energy_usage_by_county_over_time",dpi=300, bbox_inches="tight")
plt.show()

#year over year change for energy usage
total_usage_yoy = (
    data_all_years
    .groupby("data_year")["sales_megawatthours"]
    .sum()
    .reset_index()
    .sort_values("data_year")
)

total_usage_yoy["yoy_change"] = (
    total_usage_yoy["sales_megawatthours"]
    .pct_change() * 100
)

print(total_usage_yoy)

county_usage_yoy = (
    data_all_years
    .groupby(["county", "data_year"])["sales_megawatthours"]
    .sum()
    .reset_index()
    .sort_values(["county", "data_year"])
)

county_usage_yoy["yoy_change"] = (
    county_usage_yoy
    .groupby("county")["sales_megawatthours"]
    .pct_change() * 100
)

pivot_county_usage_yoy = county_usage_yoy.pivot(
    index="data_year",
    columns="county",
    values="yoy_change"
)

plt.figure()
pivot_county_usage_yoy.plot(legend=False)
plt.xlabel("Year")
plt.ylabel("Year-over-Year Change (%)")
plt.title("Year-over-Year Change in Total Usage by County")
plt.savefig("figure_8_yoy_energy_usage_change_by_county",dpi=300, bbox_inches="tight")
plt.show()

#adding a bar chart to clarify above percent change in usage by county
energy_by_county_year = (
    data_all_years
    .groupby(["county", "data_year"])["sales_megawatthours"]
    .sum()
    .reset_index()
)

energy_by_county_year_pivot = energy_by_county_year.pivot(
    index="county",
    columns="data_year",
    values="sales_megawatthours"
)

energy_by_county_year_pivot.plot(kind="bar", stacked=False)

plt.xlabel("Year")
plt.ylabel("Total Usage (Megawatthours)")
plt.title("Total Usage by County Over Time")
plt.xticks(rotation=45)
plt.legend(title="County")
plt.savefig("figure_9_total_energy_usage_by_county",dpi=300, bbox_inches="tight")
plt.show()

"""##Median income changes analysis"""

#year over year median income change
total_income_yoy = (
    data_all_years
    .groupby("data_year")["median_income"]
    .mean()
    .reset_index()
    .sort_values("data_year")
)

total_income_yoy["pct_income_change"] = (
    total_income_yoy["median_income"]
    .pct_change() * 100
)

print(total_income_yoy)

#year over year change by county for income
county_income_yoy = (
    data_all_years
    .groupby(["county", "data_year"])["median_income"]
    .mean()
    .reset_index()
    .sort_values(["county", "data_year"])
)

county_income_yoy["pct_income_change"] = (
    county_income_yoy
    .groupby("county")["median_income"]
    .pct_change() * 100
)
print(county_income_yoy)

county_income_yoy_pivot = county_income_yoy.pivot(
    index="data_year",
    columns="county",
    values="pct_income_change"
)

plt.figure
county_income_yoy_pivot.plot(legend=False)
plt.xlabel("Year")
plt.ylabel("Year-over-Year %)")
plt.title("Year-over-Year Change in Median Income by County")
plt.savefig("figure_10_yoy_median_income_by_county",dpi=300, bbox_inches="tight")
plt.show()

comparison_yoy = pd.merge(
    total_usage_yoy[["data_year", "yoy_change"]],
    total_income_yoy[["data_year", "pct_income_change"]],
    on="data_year"
)

print(comparison_yoy)

comparison_yoy["growth_gap"] = (
    comparison_yoy["yoy_change"] - comparison_yoy["pct_income_change"]
)
print(comparison_yoy)

"""##Mortgage data review

###2010/2015
"""

#need to change counts to percentages
data_2010_2015["total_housholds"] = (
    data_2010_2015["less than 30 percent income in housing cost"] +
    data_2010_2015["30 to 50 percent income in housing cost"] +
    data_2010_2015["greater than 50 percent income in housing cost"]
)

for col in [
    "less than 30 percent income in housing cost",
    "30 to 50 percent income in housing cost",
    "greater than 50 percent income in housing cost"
]:
    data_2010_2015[col + "_pct"] = (
    data_2010_2015[col] / data_2010_2015["total_housholds"]
    )

data_2010_2015

#making columns clear for correlation
data_2010_2015["affordable_rate"] = data_2010_2015["less than 30 percent income in housing cost_pct"]
data_2010_2015["burdend_rate"] = data_2010_2015["30 to 50 percent income in housing cost_pct"]
data_2010_2015["unaffordable_rate"] = data_2010_2015["greater than 50 percent income in housing cost_pct"]

#correlation of columns
data_2010_2015[["Median Income","affordable_rate", "burdend_rate", "unaffordable_rate"]].corr()

"""The above results breakdown:
median income to affordable_rate has a weak negative relationship, which means as the median income increase the percent of homes with affordable rent actually decreases instead of increasing.
median income to burdened_rate has a moderate positive relationship, which means and median income increases the rent becomes a larger part of income not lower. So counties with higher income actual has higher financial strain.
median income to unaffordable rate has a weak positive relationship, which means there is a slightly higher tendency for high income to have a severe housing burden.
Please remeber this in for the years 2010 and 2015, further analysis is needed.
"""

data_2010_2015.columns = data_2010_2015.columns.str.lower().str.replace(" ", "_")
data_1015 = data_2010_2015.sort_values(["county", "data_year"])

col_1015 = "30_to_50_percent_income_in_housing_cost"

data_1015["housing_yoy_change"] = (
    data_1015
    .groupby("county")[col_1015]
    .pct_change() * 100
)

housing_yoy_1015 = data_1015[["county", "data_year", "housing_yoy_change"]]

housing_yoy_1015.dropna(inplace=True)

housing_yoy_1015

"""###2018/2020/2024"""

#need to change counts to percentages
data_2018_2020_2024["total_housholds"] = (
    data_2018_2020_2024["less than 20 percent income in housing cost"] +
    data_2018_2020_2024["20 to 29 percent income in housing cost"] +
    data_2018_2020_2024["greater than 30 percent income in housing cost"]
)

for col in [
    "less than 20 percent income in housing cost",
    "20 to 29 percent income in housing cost",
    "greater than 30 percent income in housing cost"
]:
    data_2018_2020_2024[col + "_pct"] = (
    data_2018_2020_2024[col] / data_2018_2020_2024["total_housholds"]
    )

data_2018_2020_2024

#making columns clear for correlation
data_2018_2020_2024["affordable_rate"] = data_2018_2020_2024["less than 20 percent income in housing cost_pct"]
data_2018_2020_2024["burdend_rate"] = data_2018_2020_2024["20 to 29 percent income in housing cost_pct"]
data_2018_2020_2024["unaffordable_rate"] = data_2018_2020_2024["greater than 30 percent income in housing cost"]

#correlation of columns
data_2018_2020_2024[["Median Income","affordable_rate", "burdend_rate", "unaffordable_rate"]].corr()

data_2018_2020_2024.columns = data_2018_2020_2024.columns.str.lower().str.replace(" ", "_")
data_182024 = data_2018_2020_2024.sort_values(["county", "data_year"])

col_182024 = "20_to_29_percent_income_in_housing_cost"

data_182024["housing_yoy_change"] = (
    data_182024
    .groupby("county")[col_182024]
    .pct_change() * 100
)

housing_yoy_182024 = data_182024[["county", "data_year", "housing_yoy_change"]]

housing_yoy_182024.dropna(inplace=True)

housing_yoy_182024

"""##Price per kilowatt review"""

#price per kilowatt examination
price_per_kilowatt= (
    data_all_years
    .groupby(["county","data_year"])["price_per_kwh"]
    .mean()
    .reset_index()
)

price_per_kilowatt_pivot = price_per_kilowatt.pivot(
    index="county",
    columns="data_year",
    values="price_per_kwh"
)

plt.figure()
price_per_kilowatt_pivot.plot(kind="bar", stacked=False, legend=False)
plt.xlabel("Year")
plt.ylabel("Price per Kilowatt")
plt.title("Price per Kilowatt by County by Year")
plt.xticks(rotation=45)
plt.savefig("figure_11_price_by_count_year",dpi=300, bbox_inches="tight")
plt.show()

#yoy change for price per kilowatt
price_per_kilowatt["pct_change_price"] = (
    price_per_kilowatt
    .groupby("county")["price_per_kwh"]
    .pct_change() * 100
)

price_yoy_pivot = price_per_kilowatt.pivot(
    index="county",
    columns="data_year",
    values="pct_change_price"
)

price_yoy_pivot

"""##Comparison between increases is need to see how they are related"""

usage_yoy = county_usage_yoy.rename(columns={"yoy_change": "usage_yoy_change"})
income_yoy = county_income_yoy.rename(columns={"pct_income_change": "income_yoy_change"})
price_yoy = price_per_kilowatt.rename(columns={"pct_change_price": "price_yoy_change"})

combined_yoy = usage_yoy.merge(
    income_yoy,
    on=["county", "data_year"]
    ).merge(
    price_yoy,
    on=["county", "data_year"]
)

combined_yoy = combined_yoy.dropna()
combined_yoy

#dropping unneccessary columns
columns_to_drop = [
    "sales_megawatthours",
    "median_income",
    "price_per_kwh"
]

combined_yoy = combined_yoy.drop(columns=columns_to_drop)
combined_yoy

#correlation matrix to see how the changes relate to each other
correlation_yoy = combined_yoy[[
    "usage_yoy_change",
    "income_yoy_change",
    "price_yoy_change"
]].corr()
print(correlation_yoy)

#checking to see if income to price correlation is time trend or true correlation
combined_yoy.groupby("data_year").mean(numeric_only=True)

combined_yoy_chart = (combined_yoy.groupby("data_year").mean(numeric_only=True).reset_index())

plt.figure(figsize=(10, 6))
plt.plot(combined_yoy_chart["data_year"], combined_yoy_chart["usage_yoy_change"], marker="o", label="Usage % Change")
plt.plot(combined_yoy_chart["data_year"], combined_yoy_chart["income_yoy_change"], marker="*", label="Income % Change")
plt.plot(combined_yoy_chart["data_year"], combined_yoy_chart["price_yoy_change"], marker="D", label="Price % Change")

plt.xlabel("Year")
plt.ylabel("Percentage Change")
plt.title("Percentage Change in Usage, Income, and Price Over Time")
plt.legend()
plt.grid(True)
plt.axhline(0)
plt.savefig("figure_12_yoy_usage_income_price",dpi=300, bbox_inches="tight")
plt.show()

"""##Adding Housing data to comparison"""

#adding 2010/2015 housing data to combined yoy data
combined_1015 = combined_yoy.merge(
    housing_yoy_1015,
    on=["county", "data_year"],
    how="inner"
).dropna()

#adding 2010/2015 housing data to combined yoy data
combined_182024 = combined_yoy.merge(
    housing_yoy_182024,
    on=["county", "data_year"],
    how="inner"
).dropna()

#running correlation on yoy change 2010/2015
corr_1015 = combined_1015[[
    "usage_yoy_change",
    "income_yoy_change",
    "price_yoy_change",
    "housing_yoy_change"
]].corr()
print(corr_1015)

#running correlation on yoy change 2018/2020/2024
corr_182024 = combined_182024[[
    "usage_yoy_change",
    "income_yoy_change",
    "price_yoy_change",
    "housing_yoy_change"
]].corr()
print(corr_182024)

"""## Adding energy burden to data frames"""

#yoy change in energy burden
burden_yoy = (
    data_all_years
    .groupby(["county", "data_year"])["energy_burden"]
    .mean()
    .reset_index()
    .sort_values(["county", "data_year"])
)

burden_yoy["burden_yoy_change"] = (
    burden_yoy
    .groupby("county")["energy_burden"]
    .pct_change() * 100
)

burden_yoy = burden_yoy[[
    "county",
    "data_year",
    "burden_yoy_change"
]]

burden_yoy.dropna(inplace=True)

burden_yoy

#adding everything together
combined_1015 = combined_1015.merge(
    burden_yoy,
    on=["county", "data_year"],
    how="left"
)
combined_1015.head()

#adding everything together
combined_182024 = combined_182024.merge(
    burden_yoy,
    on=["county", "data_year"],
    how="left"
)

combined_182024.head()

#running correlation on yoy change 2010/2015
corr_1015_housing = combined_1015[[
    "usage_yoy_change",
    "income_yoy_change",
    "price_yoy_change",
    "housing_yoy_change",
    "burden_yoy_change"
]].corr()
print(corr_1015_housing)

#running correlation on yoy change 2018/2020/2024
corr_182024_housing = combined_182024[[
    "usage_yoy_change",
    "income_yoy_change",
    "price_yoy_change",
    "housing_yoy_change",
    "burden_yoy_change"
]].corr()
print(corr_182024_housing)

"""#Final Analysis"""

#add energy burden to final data set
combined_yoy = combined_yoy.merge(
    burden_yoy,
    on=["county", "data_year"],
    how="left"
)
#adding housing data for 2010/2015 to final data set
combined_yoy = combined_yoy.merge(
    housing_yoy_1015.rename(columns={"housing_yoy_change": "housing_1015_yoy"}),
    on=["county", "data_year"],
    how="left"
)

#adding housing data for 2018/2020/2024 to final data set
combined_yoy = combined_yoy.merge(
    housing_yoy_182024.rename(columns={"housing_yoy_change": "housing_1824_yoy"}),
    on=["county", "data_year"],
    how="left"
)

combined_yoy.head()

#final chart of combined data
final_chart = (
    combined_yoy
    .groupby("data_year")
    .mean(numeric_only=True)
    .reset_index()
)

plt.figure(figsize=(10, 6))
plt.plot(final_chart["data_year"], final_chart["usage_yoy_change"], marker="o", label="Usage % Change")
plt.plot(final_chart["data_year"], final_chart["income_yoy_change"], marker="*", label="Income % Change")
plt.plot(final_chart["data_year"], final_chart["price_yoy_change"], marker="D", label="Price % Change")
plt.plot(final_chart["data_year"], final_chart["burden_yoy_change"], marker="s", label="Energy Bruden % Change")
plt.plot(final_chart["data_year"], final_chart["housing_1015_yoy"], marker="^", label="Housing % Change 2010/2015")
plt.plot(final_chart["data_year"], final_chart["housing_1824_yoy"], marker="v", label="Housing % Change 2018/2020/2024")
plt.axhline(0)
plt.xlabel("Year")
plt.ylabel("Percentage Change (%)")
plt.title("Year over Year Changes Across Energy, Income, and Housing")
plt.legend()
plt.grid(True)
plt.xticks(final_chart["data_year"])
plt.tight_layout()
plt.savefig("figure_13_yoy_changes_energy_income_housing",dpi=300, bbox_inches="tight")
plt.show()

#final linear regressions data sets
final_1015 = combined_yoy.dropna(subset=["housing_1015_yoy"])
final_1824 = combined_yoy.dropna(subset=["housing_1824_yoy"])

"""This model below (2010-2015) predicts changes in housing burden using usage, income, and price. Energy burden was excluded due to near collinearity with income."""

#Final linear regression for 2010/2015

X_1015 = final_1015[[
    "usage_yoy_change",
    "income_yoy_change",
    "price_yoy_change"
]]
y_1015 = final_1015["housing_1015_yoy"] #not doing energy burden here as it is redunant(because it is a derived variable)

model_1015 = LinearRegression()
model_1015.fit(X_1015, y_1015)

print("2010-2015 Model")
print("Intercept:", model_1015.intercept_)
print("Coefficients:", model_1015.coef_)

#Final prediction for 2010-2015
y_pred_1015 = model_1015.predict(X_1015)

print("R2 score 2010-2015:", r2_score(y_1015,y_pred_1015))

"""This model above (2010-2015) shows low explanatory power, suggesting that the selected variables do not strongly predict housing burden changes in this period. This may be due to limited data or less developed relationships between variables.

This model below (2018-2024) predicts changes in energy burden using usage, income, and price. Housing varaiables were excluded to avoid redundancy and multicollinearity.
"""

#Final linear regression for 2018-2024
X_1824 = final_1824[[
    "usage_yoy_change",
    "income_yoy_change",
    "price_yoy_change"
]]

y_1824 = final_1824["burden_yoy_change"]

model_1824 = LinearRegression()
model_1824.fit(X_1824, y_1824)

print("2018-2024 Model")
print("Intercept:", model_1824.intercept_)
print("Coefficients:", model_1824.coef_)

#Final prediction for 2018-2024
y_pred_1824 = model_1824.predict(X_1824)

print("R2 score 2018-2024:", r2_score(y_1824,y_pred_1824))

"""This model above (2018-2024) shows strong explanatory power (R2 = 0.93), indicating that energy burden can be effectively predicted using the selected variables. Income has the strongest negative relationship with energy burden, suggesting that increases in income significantly reduce affordability pressure. Price shows a strong positive relationship, while usage has minimal impact.

##Final Interpretation
The analysis indicates that energy affordability is primarily driven by income and price changes, with usage playing a minimal role. Over time, relationships between variables become more structured, resulting in a more predictable system in the later period.
"""

combined_yoy.to_csv("combined_yoy.csv", index=False)
final_1015.to_csv("final_1015.csv", index=False)
final_1824.to_csv("final_1824.csv", index=False)