# -*- coding: utf-8 -*-
"""Arizona_energy_burden_Feature_Engineering_all_years.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fu4panhE_t0ViM9IGbSVpShYCmavOfY_
"""

#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

features_2010_2015 = pd.read_csv('2010_2015_data.csv')

features_2018_2020_2024 = pd.read_csv('2018_2020_2024_data.csv')

#combine all years
data_all_years = pd.concat([features_2010_2015, features_2018_2020_2024], ignore_index=True)
data_all_years

#drop housing columns
cols_to_drop = [col for col in data_all_years.columns if 'housing' in col.lower()]
data_all_years = data_all_years.drop(columns=cols_to_drop)
data_all_years

data_all_years.columns = data_all_years.columns.str.replace(' ', '_').str.lower()

data_all_years

data_all_years.to_csv('data_all_years.csv', index=False)
from google.colab import files
files.download('data_all_years.csv')