# -*- coding: utf-8 -*-
"""Arizona_energy_burden_Feature_Engineering_2010_2015.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110IzQYtTlZh16haJgh5rHcBkWM4Yk5AT
"""

#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

data_2010 = pd.read_csv('/content/clean_year_2010.csv')
data_2010.head()

data_2015 = pd.read_csv('/content/clean_year_2015.csv')
data_2015.head()

#merge datasets into one
data_10_15_merged = pd.concat([data_2010, data_2015], ignore_index=True)
data_10_15_merged

"""Standardizing data"""

#clean year column
data_10_15_merged["Data Year"] = data_10_15_merged["Data Year"].astype(float).astype(int)

non_numeric_cols = ["County", "Data Year"]
#clean all columns
for col in data_10_15_merged.columns:
  if col not in non_numeric_cols:
    data_10_15_merged[col] = pd.to_numeric(
        data_10_15_merged[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip(),
        errors="coerce"
    )

#convert to float
data_10_15_merged = data_10_15_merged.astype({
    col: "float" for col in data_10_15_merged.columns if col not in non_numeric_cols
})

print(data_10_15_merged.dtypes)

"""#Feature Engineering"""

#Energy cost per customer
data_10_15_merged["avg_energy_cost_per_customer"] = (
    data_10_15_merged["Revenues Thousand Dollars"] * 1000
    / data_10_15_merged["Customers Count"]
)

#Energy used per customer
data_10_15_merged["avg_kwh_per_customer"] = (
    data_10_15_merged["Sales Megawatthours"] *1000
    / data_10_15_merged["Customers Count"]
)

#Price per kilowatt hour
data_10_15_merged["price_per_kwh"] = (data_10_15_merged["Revenues Thousand Dollars"] * 1000) / (data_10_15_merged["Sales Megawatthours"] * 1000)

#Estimated Energy Burden
data_10_15_merged["energy_burden"] = data_10_15_merged["avg_energy_cost_per_customer"]  / data_10_15_merged["Median Income"]

#Total energy per capital
data_10_15_merged["kwh_per_capita"] = (data_10_15_merged["Sales Megawatthours"] * 1000) / data_10_15_merged["Population"]

data_10_15_merged

data_10_15_merged.to_csv('2010_2015_data.csv', index=False)
from google.colab import files
files.download('2010_2015_data.csv')