# -*- coding: utf-8 -*-
"""Arizona_energy_burden_Feature_Engineering_2018_2020_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWWtsIXH2xrSt1TydAzdRQnHChlBF6Mp
"""

#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

data_2018 = pd.read_csv('/content/clean_year_2018.csv')
data_2018.head()

data_2020 = pd.read_csv('/content/clean_year_2020.csv')
data_2020.head()

data_2024 = pd.read_csv('/content/clean_year_2024.csv')
data_2024.head()

#merge datasets into one
data_18_20_24_merged = pd.concat([data_2018, data_2020, data_2024], ignore_index=True)
data_18_20_24_merged

"""Standardizing data"""

#clean year column
data_18_20_24_merged["Data Year"] = data_18_20_24_merged["Data Year"].astype(float).astype(int)

non_numeric_cols = ["County", "Data Year"]
#clean all columns
for col in data_18_20_24_merged.columns:
  if col not in non_numeric_cols:
    data_18_20_24_merged[col] = pd.to_numeric(
        data_18_20_24_merged[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip(),
        errors="coerce"
    )

#convert to float
data_18_20_24_merged = data_18_20_24_merged.astype({
    col: "float" for col in data_18_20_24_merged.columns if col not in non_numeric_cols
})

print(data_18_20_24_merged.dtypes)

"""#Feature Engineering"""

#Energy cost per customer
data_18_20_24_merged["avg_energy_cost_per_customer"] = (
    data_18_20_24_merged["Revenues Thousand Dollars"] * 1000
    / data_18_20_24_merged["Customers Count"]
)

#Energy used per customer
data_18_20_24_merged["avg_kwh_per_customer"] = (
    data_18_20_24_merged["Sales Megawatthours"] *1000
    / data_18_20_24_merged["Customers Count"]
)

#Price per kilowatt hour
data_18_20_24_merged["price_per_kwh"] = (data_18_20_24_merged["Revenues Thousand Dollars"] * 1000) / (data_18_20_24_merged["Sales Megawatthours"] * 1000)

#Estimated Energy Burden
data_18_20_24_merged["energy_burden"] = data_18_20_24_merged["avg_energy_cost_per_customer"]  / data_18_20_24_merged["Median Income"]

#Total energy per capital
data_18_20_24_merged["kwh_per_capita"] = (data_18_20_24_merged["Sales Megawatthours"] * 1000) / data_18_20_24_merged["Population"]

#check final output
data_18_20_24_merged

data_18_20_24_merged.to_csv('2018_2020_2024_data.csv', index=False)
from google.colab import files
files.download('2018_2020_2024_data.csv')